services:
  app:
    image: node:20
    container_name: testExpress
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    command: "npm install && node index.js"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: testMongoDB
    ports:
      - '27017:27017'